### ISSUE TITLE
Question about Auto-Restarter

### ISSUE THREAD

**Issue by mathas5** [SteamTimeIdler/stidler#10]
Hello,

Yes it's me again. I have Auto-Restarter turned on and it should automatically "auto-restart" your idle if you play a game or simply Steam goes down. If this happens I'm getting a lot of shared secret codes on my mobile. For me it's normal. But I'm waiting for 30 minutes and nothing happens. So my question is - Do I have to wait longer? 

Thank you for your support,

Matas

![screenshot_20170707_181158](https://user-images.githubusercontent.com/29887480/27964101-c0e6b346-633f-11e7-9f6f-f425c8cb4d53.png)

**Comment by SteamTimeIdler** [comment]
Hi Matas

Using AutoRestarter with **EMAIL AUTH**:
If you have successfully started an idle once using Email Auth then you can simply enable AutoRestarter and it will work out of the box.

Using AutoRestarter with **MOBILE AUTH**:
Mobile auth requires a little bit more work.

1. You need to extract your shared_secret code from your phone. [See here](https://github.com/SteamTimeIdler/stidler/wiki/Getting-your-'shared_secret'-code-for-use-with-Auto-Restarter-on-Mobile-Authentication)
_Please note: Your SHARED_SECRET is NOT the same as your Mobile Auth Code_
2. Enter your shared_secret into the shared_secret box
3. Enter your mobile auth code as well into the auth code box
4. Start your idle before your auth code changes again.
5. Leave the idle running for 30 minutes (Over 2 AutoRestarter cycles)
6. You are now free to start a game and finish it for the next cycle

_Please note as well: If you end your idle by playing a game 8 minutes or less before the next cycle you will not be added to the AutoRestarter queue for that 15 minute interval but you will be in the next one_

That image stating you don't need the auth code if you have your shared_secret code is a mistake and has been updated, thank you.

--------------------------------------------------------

- **Email auth** is easy because we can generate a file through Steam when you start your idle for the first time. We can then pass this to Steam as verification without the need of another code. This means you can manage/start your idles without any codes at all.
- **Mobile auth** requires the code every log in. If Steam updates or goes down or you play a game we have no way of restarting your idle without getting your auth code. The shared_secret code is a code that allows us to generate your auth_code automatically without you needing to be there to start it.

--------------------------------------------------------

Soon we are releasing a new Control Panel which will make this much easier to use/do. Stay tuned :)

Useful links:
- [Getting your shared_secret code from your phone](https://github.com/SteamTimeIdler/stidler/wiki/Getting-your-'shared_secret'-code-for-use-with-Auto-Restarter-on-Mobile-Authentication)
- [Steam direct contact - Make sure you leave a comment](http://steamcommunity.com/id/tirone)

~ Ti

**Comment by mathas5** [comment]
Hello Ti,

I did not know that you need to put your mobile auth code as well as shared_secret code. I will admit that this control panel is a little bit confusing. I'm waiting for the new Control Panel!

Thank you for the wonderful support!

Matas
