### ISSUE TITLE
Farming

### ISSUE THREAD

**Issue by Elite911** [SteamTimeIdler/stidler#6]
Possible bug? When I launch the card farmer it doesn't launch any games, it also says attempting to log in, logged in repeatedly. I'm using mobile authenticator as well.

Here's the log:

58 seconds ago - Attempting login
58 seconds ago - Logged in
58 seconds ago - Configuring settings
1 minute ago - Configuring settings
1 minute ago - Logged in
1 minute ago - Attempting login
15 seconds ago - Get apps
15 seconds ago - Playtime checks
15 seconds ago - Idling 90 apps for up to 2 hours. Once complete, the card farmer shall start.
2 minutes ago - Configuring settings
2 minutes ago - Logged in
![log](https://cloud.githubusercontent.com/assets/5841305/24092444/3cc79b6c-0d9e-11e7-8d7c-73a8593f770b.jpg)

**Comment by SteamTimeIdler** [comment]
Hi Elite

I will preface this message by saying we are releasing a fully upgraded site soon where all this will work much better!

From your logs (They seem to be loaded in the wrong order which I'll look into), the latest message was 15 seconds ago "_Idling 90 apps for up to 2 hours. Once complete, the card farmer shall start._". Before you are able to gain cards on a game you are required (By Steam) to have at least 2 hours on said game. SteamTimeIdler is now idling those games to 2 hours. 

An important thing to note, **Card Farmer automatically idles while appearing offline**. This is to stop your profile from spamming all your friends as the games switch often. This stops spam notifications to all your friends.

Answer: Looks like it is running, just leave it be. It _looks_ like it isn't running because Card Farmer appears offline automatically and the log order is wrong.

Cheers

**Comment by Elite911** [comment]
Thanks. Can't wait to see the new site.

Also, there's a small issue, when you click the clear logs (both chat and farming) it doesn't clear the logs at all, it's like the button is inactive.

**Comment by SteamTimeIdler** [comment]
Thanks, we'll make sure to have that all sorted on the new control panel :)
